/****** Object:  Database [FoodOrderDB]    Script Date: 11/15/2025 2:41:52 AM ******/
CREATE DATABASE [FoodOrderDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FoodOrderDB', FILENAME = N'C:\Users\golia\FoodOrderDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FoodOrderDB_log', FILENAME = N'C:\Users\golia\FoodOrderDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [FoodOrderDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FoodOrderDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FoodOrderDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FoodOrderDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FoodOrderDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FoodOrderDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FoodOrderDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FoodOrderDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [FoodOrderDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FoodOrderDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FoodOrderDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FoodOrderDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FoodOrderDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FoodOrderDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FoodOrderDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FoodOrderDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FoodOrderDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FoodOrderDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FoodOrderDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FoodOrderDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FoodOrderDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FoodOrderDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FoodOrderDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FoodOrderDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FoodOrderDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FoodOrderDB] SET  MULTI_USER 
GO
ALTER DATABASE [FoodOrderDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FoodOrderDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FoodOrderDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FoodOrderDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FoodOrderDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FoodOrderDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FoodOrderDB] SET QUERY_STORE = OFF
GO
/****** Object:  Table [dbo].[OrderItems]    Script Date: 11/15/2025 2:41:52 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderItems](
	[ItemID] [int] IDENTITY(1,1) NOT NULL,
	[OrderID] [int] NULL,
	[ItemName] [nvarchar](100) NULL,
	[Quantity] [int] NULL,
	[Price] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 11/15/2025 2:41:52 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[OrderID] [int] IDENTITY(1,1) NOT NULL,
	[CustomerName] [nvarchar](100) NULL,
	[TotalAmount] [decimal](10, 2) NULL,
	[OrderType] [nvarchar](50) NULL,
	[DateOrdered] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[OrderItems] ON 
GO
INSERT [dbo].[OrderItems] ([ItemID], [OrderID], [ItemName], [Quantity], [Price]) VALUES (2, 2, N'Burger', 1, CAST(25.00 AS Decimal(10, 2)))
GO
INSERT [dbo].[OrderItems] ([ItemID], [OrderID], [ItemName], [Quantity], [Price]) VALUES (3, 2, N'Burger', 1, CAST(25.00 AS Decimal(10, 2)))
GO
INSERT [dbo].[OrderItems] ([ItemID], [OrderID], [ItemName], [Quantity], [Price]) VALUES (4, 3, N'Chocolate', 1, CAST(10.00 AS Decimal(10, 2)))
GO
INSERT [dbo].[OrderItems] ([ItemID], [OrderID], [ItemName], [Quantity], [Price]) VALUES (5, 3, N'Cake', 2, CAST(100.00 AS Decimal(10, 2)))
GO
SET IDENTITY_INSERT [dbo].[OrderItems] OFF
GO
SET IDENTITY_INSERT [dbo].[Orders] ON 
GO
INSERT [dbo].[Orders] ([OrderID], [CustomerName], [TotalAmount], [OrderType], [DateOrdered]) VALUES (2, N'Gabbie Molos', CAST(25.00 AS Decimal(10, 2)), N'Bulk', CAST(N'2025-11-15T01:31:47.777' AS DateTime))
GO
INSERT [dbo].[Orders] ([OrderID], [CustomerName], [TotalAmount], [OrderType], [DateOrdered]) VALUES (3, N'Liam Go', CAST(210.00 AS Decimal(10, 2)), N'Bulk', CAST(N'2025-11-15T02:23:06.187' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Orders] OFF
GO
ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD FOREIGN KEY([OrderID])
REFERENCES [dbo].[Orders] ([OrderID])
GO
ALTER DATABASE [FoodOrderDB] SET  READ_WRITE 
GO
